module WebAPI.Dota.Internal.SharedFields where

import Control.Lens.TH.SharedFields

generateFields
  [ "Abilities"
  , "AccountID"
  , "Amount"
  , "Assists"
  , "Bans"
  , "BarracksState"
  , "Complete"
  , "Cost"
  , "Deaths"
  , "Denies"
  , "Description"
  , "DireSeriesWins"
  , "DireTeam"
  , "Duration"
  , "Gold"
  , "Gpm"
  , "HeroID"
  , "Identifier"
  , "Itemdef"
  , "Items"
  , "Kills"
  , "LastHits"
  , "LeagueID"
  , "LeagueTier"
  , "Leagues"
  , "Level"
  , "LobbyID"
  , "LocalName"
  , "Logo"
  , "Matches"
  , "Name"
  , "Picks"
  , "Players"
  , "Position"
  , "RadiantSeriesWins"
  , "RadiantTeam"
  , "Recipe"
  , "RespawnTimer"
  , "RoshTimer"
  , "Score"
  , "Scoreboard"
  , "SecretShop"
  , "SeriesType"
  , "SideShop"
  , "Slot"
  , "Spectators"
  , "StreamDelay"
  , "Team"
  , "TowerState"
  , "Url"
  , "Xpm" ]
